### ISSUE TITLE
Friendly Suggestion

### ISSUE THREAD

**Issue by Jkosio23** [ManasMods/CloudSettings#7]
Please for the love of everyone with cyber paranoia put an extended description of the mod in the cloud settings popup, including a link to the mod page. I only found out about this mod via a reddit post with someone concerned that this was malware. I briefly skimmed through the code and think it's legit but not everyone can tell from a glance.

**Comment by Charismara** [comment]
thank you for your suggestion. I'll think about a way to prevent people from getting scared :)

**Comment by Charismara** [comment]
done in 1.1.0.0
